project:
  type: website
  output-dir: _site

website:
  title: "THOMAS R VARGAS"
  google-analytics: "G-QK7N03YBK4"
  favicon: images/favicon.png
  
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - icon: github
        href: https://github.com/thomasvargas
        aria-label: "GitHub"
      - icon: linkedin
        href: https://www.linkedin.com/in/thomas-vargas-a7110325/
        aria-label: "LinkedIn"
      - icon: google
        href: https://scholar.google.ca/citations?user=5oWJ6bQAAAAJ&hl=en
        aria-label: "Google Scholar"

  page-footer:
    left: "Â© 2025 Thomas R. Vargas"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    mainfont: "Inter"
    fontsize: 1.1em