project:
  type: website
  output-dir: _site

website:
  title: "THOMAS R VARGAS"
  google-analytics: "G-QK7N03YBK4" # <--- Paste here
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - icon: github
        href: https://github.com/thomasvargas

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    mainfont: "Inter"
    fontsize: 1.1em