[build]
  command = """
    curl -L -o quarto.tar.gz https://github.com/quarto-dev/quarto-cli/releases/download/v1.5.57/quarto-1.5.57-linux-amd64.tar.gz && \
    mkdir -p .quarto-bin && \
    tar -xzf quarto.tar.gz -C .quarto-bin --strip-components=1 && \
    ./.quarto-bin/bin/quarto render
  """
  publish = "_site"

[context.production.environment]
  QUARTO_PRINT_STACK = "true"